name: 'Release Issues'
description: 'Creates issues that help track releases and deploy them'
inputs:
  token:
    description: 'GitHub token with repo scope'
    required: true
    default: ${{ github.token }}
  settings_file:
    description: 'Path to the settings file'
    required: true
    default: .release-settings.yml
runs:
  using: 'node16'
  main: 'dist/index.js'
