name: 'Release Issues'
description: 'Creates issues that help track releases and deploy them'
inputs:
  token:
    description: 'GitHub token with repo scope'
    required: true
    default: ${{ github.token }}
  settings:
    description: 'Settings file contents'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
