name: 'Commit Message Validation'
description: 'Validates commit messages'
inputs:
  github_token:
    description: 'GitHub token with repo scope'
    required: true
    default: ${{ secrets.GITHUB_TOKEN }}
  pull_request:
    description: 'The pull request number'
    required: true
    default: ${{ github.event.number }}
runs:
  using: 'node16'
  main: 'src/index.js'
