name: Check Package

on:
  workflow_call:
    inputs:
      directory:
        type: string
        required: true
        description: The working directory to run the check in

jobs:
  lint_package:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          path: .
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          registry-url: 'https://npm.pkg.github.com'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        working-directory: ${{ inputs.directory }}
        run: npm install
      - name: Lint project
        working-directory: ${{ inputs.directory }}
        run: npm run lint
  test_package:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          path: .
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          registry-url: 'https://npm.pkg.github.com'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        working-directory: ${{ inputs.directory }}
        run: npm install
      - name: Test Prettier Config
        working-directory: ${{ inputs.directory }}
        run: npm run test
