name: Publish Package

on:
  workflow_call:
    inputs:
      directory:
        type: string
        required: true
        description: The working directory to run the check in
      build:
        type: boolean
        required: false
        default: false
        description: Whether the package requires a build
      version:
        type: string
        required: true
        default: '1.0.0'
        description: The version tag to publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          path: .

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          registry-url: 'https://npm.pkg.github.com'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm install

      - name: Build
        if: ${{ inputs.build }}
        working-directory: ${{ inputs.directory }}
        run: npm run build

      - name: Package Version
        working-directory: ${{ inputs.directory }}
        run: npm version ${{ inputs.version }} --no-git-tag-version

      - name: Publish
        working-directory: ${{ inputs.directory }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
